# permissions for end users to view backstagetenantconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstagetenantconfig-viewer-role
rules:
- apiGroups:
  - tenants.gitops.pro
  resources:
  - backstagetenantconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenants.gitops.pro
  resources:
  - backstagetenantconfigs/status
  verbs:
  - get
